# Generated by Django 2.0.7 on 2018-07-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('t1_name', models.CharField(max_length=10)),
                ('t2_name', models.CharField(max_length=10)),
                ('t1_batAvg', models.FloatField()),
                ('t2_batAvg', models.FloatField()),
                ('t1_OBP', models.FloatField()),
                ('t2_OBP', models.FloatField()),
                ('t1_OPS', models.FloatField()),
                ('t2_OPS', models.FloatField()),
                ('t1_slug', models.FloatField()),
                ('t2_slug', models.FloatField()),
                ('t1_ERA', models.FloatField()),
                ('t2_ERA', models.FloatField()),
                ('t1_winner', models.IntegerField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
