# Generated by Django 2.0.7 on 2018-08-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0002_auto_20180708_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1_name', models.CharField(max_length=10)),
                ('t2_name', models.CharField(max_length=10)),
                ('t1_batAvg', models.FloatField()),
                ('t2_batAvg', models.FloatField()),
                ('t1_OBP', models.FloatField()),
                ('t2_OBP', models.FloatField()),
                ('t1_OPS', models.FloatField()),
                ('t2_OPS', models.FloatField()),
                ('t1_slug', models.FloatField()),
                ('t2_slug', models.FloatField()),
                ('t1_ERA', models.FloatField()),
                ('t2_ERA', models.FloatField()),
            ],
        ),
    ]
