# Generated by Django 2.0.7 on 2018-07-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
