# Generated by Django 2.0.7 on 2018-08-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0006_auto_20180823_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todaygame',
            name='prediction',
        ),
        migrations.AddField(
            model_name='todaygame',
            name='predictionInt',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todaygame',
            name='predictionTeam',
            field=models.CharField(default='ERR', max_length=10),
            preserve_default=False,
        ),
    ]
